package enumerations;

public enum Nationality {

	USA, MEXICO, CANADA, GUATEMALA, HAITI, CUBA, DOMINICAN_REPUBLIC, HONDURAS, EL_SALVADOR, COSTA_RICA, PANAMA,
	JAMAICA, PUERTO_RICO, TRINIDAD_AND_TOBAGO, GUADELOUPE, BELIZE, BAHAMAS, MARTINIQUE, BARBADOS, SAINT_LUCIA, CURACAO,
	GRENADA, SAINT_VINCENT_AND_THE_GRENADINES, ARUBA, UNITED_STATES_VIRGIN_ISLANDS, ANTIGUA_AND_BARBUDA, DOMINICA,
	CAYMAN_ISLANDS, BERMUDA, GREENLAND, SAINT_KITTS_AND_NEVIS, SINT_MAARTEN, TURKS_AND_CAICOS_ISLANDS, SAINT_MARTIN,
	BRITISH_VIRGIN_ISLANDS, CARIBBEAN_NETHERLANDS, ANGUILLA, SAINT_BARTHELEMY, SAINT_PIERRE_AND_MIQUELON,MONTSERRAT,
	BRAZIL, COLOMBIA, ARGENTINA, PERU, VENEZUELA, CHILE, ECUADOR, BOLIVIA, PARAGUAY, URUGUAY, GUYANA, SURINAME,
	FRENCH_GUIANA, FALKLAND_ISLANDS,NICARAGUA;

}
